name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello Github Action"
      - name: Prinnt Goodbye
        run: echo "Completed Actions - bye"



         
